# Generated by Django 5.2.6 on 2025-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'JEEP'), (10, 'MERCEDES-BENZ'), (11, 'NISSAN'), (12, 'PEUGEOT'), (13, 'RENAULT'), (14, 'TOYOTA'), (15, 'VOLKSWAGEN - VW')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'PRETO'), (3, 'CINZA'), (4, 'PRATA'), (5, 'VERMELHO'), (6, 'AZUL'), (7, 'VERDE'), (8, 'AMARELO'), (9, 'LARANJA'), (10, 'ROXO'), (11, 'MARROM'), (12, 'BEGE')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'GASOLINA'), (2, 'ETANOL'), (3, 'DIESEL'), (4, 'FLEX')])),
            ],
        ),
    ]
